### ISSUE TITLE
Replying to inline-encrypted email broken?

### ISSUE THREAD

**Issue by duckdalbe** [jkraemer/mail-gpg#30]
When I'm trying to reply to an inline-pgp formatted email with `message.reply()` I'm seeing this:

```
wrong number of arguments (0 for 1..2)
/var/lib/gems/2.1.0/gems/mail-gpg-0.2.6/lib/mail/gpg/inline_decrypted_message.rb:15:in `initialize'
/var/lib/gems/2.1.0/gems/mail-2.6.4.rc2/lib/mail/message.rb:266:in `new'
/var/lib/gems/2.1.0/gems/mail-2.6.4.rc2/lib/mail/message.rb:266:in `reply'
```

I guess this is because `Mail::Message#reply` (and `Mail::Message#new`) don't require any argument, while `Mail::Gpg::InlineDecryptedMessage#new` does.

Or am I doing something wrong?

**Comment by duckdalbe** [comment]
Any idea on this?

**Comment by duckdalbe** [comment]
Replying to a formerly unencrypted but pgp/mime-signed message is broken, too. Gives the same error message.

All three of `MimeSignedMessage`, `InlineSignedMessage`, and `InlineDecryptedMessage` feature the `initialize()`-method that requires an argument, which breaks `Mail::Message#reply`.
