### ISSUE TITLE
In inline mode, fails trying to decrypt application/pgp-encrypted part

### ISSUE THREAD

**Issue by ryantate** [jkraemer/mail-gpg#32]
When mail-gpg falls back to inline mode during decryption, AND when the message is multipart, it appears mail-gpg is improperly trying to decrypt the version/control portion of the message, of type `application/pgp-encrypted`, even though the deryptable data lives only in the actual payload part of the message, of type `application/octet-stream`. This can result in an uncaught exception from GPGMe of type `GPGME::Error::NoData`. 

According to RFC 3156 (and RFC 2015 as well) the `application/pgp-encrypted` part is for "control information". https://www.ietf.org/rfc/rfc3156.txt 

However, `Mail::Gpg::InlineDecryptedMessage.new`, called from `Mail::Gpg.decrypt_pgp_inline`, called from `Mail::Gpg.decrypt`, tries to decrypt any part with a Content-Type matching EITHER `application/octet-stream` OR `application/pgp-encrypted`:

```
cipher_mail.parts.each do |part|
              p = VerifiedPart.new do |p|
                if part.has_content_type? && /application\/(?:octet-stream|pgp-encrypted)/ =~ part.mime_type
                  # encrypted attachment, we set the content_type to the generic 'application/octet-stream'
                  # and remove the .pgp/gpg/asc from name/filename in header fields
                  decrypted = GpgmeHelper.decrypt(part.decoded, options)
```

Calling GpgmeHelper.decrypt on a part of type `application/pgp-encrypted` will throw `GPGME::Error::NoData`.

For example:

```
2.2.1 :021 > m.class
 => Mail::Message 
2.2.1 :022 > m.parts[1].content_type
 => "application/pgp-encrypted; name=\"PGPMIME Versions Identification\"" 
2.2.1 :023 > Mail::Gpg::GpgmeHelper.decrypt(m.parts[1].decoded)
GPGME::Error::NoData: GPGME::Error::NoData
	from /Users/ryantate/.rvm/gems/ruby-2.2.1/gems/gpgme-2.0.12/lib/gpgme/ctx.rb:428:in `decrypt'
	from /Users/ryantate/.rvm/gems/ruby-2.2.1/gems/mail-gpg-0.2.6/lib/mail/gpg/gpgme_helper.rb:57:in `block in decrypt'
	from /Users/ryantate/.rvm/gems/ruby-2.2.1/gems/gpgme-2.0.12/lib/gpgme/ctx.rb:79:in `new'
	from /Users/ryantate/.rvm/gems/ruby-2.2.1/gems/mail-gpg-0.2.6/lib/mail/gpg/gpgme_helper.rb:51:in `decrypt'
	from (irb):23
	from /Users/ryantate/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
```

I can make a pull request/patch if you're interested in fixing this.

**Comment by jkraemer** [comment]
A pull request would indeed be nice :) thanks!

On 06/06, Ryan Tate wrote:
> When mail-gpg falls back to inline mode during decryption, AND when the message is multipart, it appears mail-gpg is improperly trying to decrypt the version/control portion of the message, of type `application/pgp-encrypted`, even though the deryptable data lives only in the actual payload part of the message, of type `application/octet-stream`. This can result in an uncaught exception from GPGMe of type `GPGME::Error::NoData`. 
> 
> According to RFC 3156 (and RFC 2015 as well) the `application/pgp-encrypted` part is for "control information". https://www.ietf.org/rfc/rfc3156.txt 
> 
> However, `Mail::Gpg::InlineDecryptedMessage.new`, called from `Mail::Gpg.decrypt_pgp_inline`, called from `Mail::Gpg.decrypt`, tries to decrypt any part with a Content-Type matching EITHER `application/octet-stream` OR `application/pgp-encrypted`:
> 
> ```
> cipher_mail.parts.each do |part|
>               p = VerifiedPart.new do |p|
>                 if part.has_content_type? && /application\/(?:octet-stream|pgp-encrypted)/ =~ part.mime_type
>                   # encrypted attachment, we set the content_type to the generic 'application/octet-stream'
>                   # and remove the .pgp/gpg/asc from name/filename in header fields
>                   decrypted = GpgmeHelper.decrypt(part.decoded, options)
> ```
> 
> Calling GpgmeHelper.decrypt on a part of type `application/pgp-encrypted` will throw `GPGME::Error::NoData`.
> 
> For example:
> 
> ```
> 2.2.1 :021 > m.class
>  => Mail::Message 
> 2.2.1 :022 > m.parts[1].content_type
>  => "application/pgp-encrypted; name=\"PGPMIME Versions Identification\"" 
> 2.2.1 :023 > Mail::Gpg::GpgmeHelper.decrypt(m.parts[1].decoded)
> GPGME::Error::NoData: GPGME::Error::NoData
> 	from /Users/ryantate/.rvm/gems/ruby-2.2.1/gems/gpgme-2.0.12/lib/gpgme/ctx.rb:428:in `decrypt'
> 	from /Users/ryantate/.rvm/gems/ruby-2.2.1/gems/mail-gpg-0.2.6/lib/mail/gpg/gpgme_helper.rb:57:in `block in decrypt'
> 	from /Users/ryantate/.rvm/gems/ruby-2.2.1/gems/gpgme-2.0.12/lib/gpgme/ctx.rb:79:in `new'
> 	from /Users/ryantate/.rvm/gems/ruby-2.2.1/gems/mail-gpg-0.2.6/lib/mail/gpg/gpgme_helper.rb:51:in `decrypt'
> 	from (irb):23
> 	from /Users/ryantate/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
> ```
> 
> I can make a pull request/patch if you're interested in fixing this.
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jkraemer/mail-gpg/issues/32

-- 
Jens Kr�mer
https://jkraemer.net/
