### ISSUE TITLE
gpgme: NULL pointer given

### ISSUE THREAD

**Issue by corny** [jkraemer/mail-gpg#46]
I get a lot of `ArgumentError: NULL pointer given` when sending signed emails:

```
ruby/2.3.0/gems/gpgme-2.0.12/lib/gpgme/ctx.rb:480:in `gpgme_op_sign_result'
ruby/2.3.0/gems/gpgme-2.0.12/lib/gpgme/ctx.rb:480:in `sign_result'
ruby/2.3.0/gems/gpgme-2.0.12/lib/gpgme/crypto.rb:251:in `rescue in block in sign'
ruby/2.3.0/gems/gpgme-2.0.12/lib/gpgme/crypto.rb:248:in `block in sign'
ruby/2.3.0/gems/gpgme-2.0.12/lib/gpgme/ctx.rb:79:in `new'
ruby/2.3.0/gems/gpgme-2.0.12/lib/gpgme/crypto.rb:242:in `sign'
ruby/2.3.0/gems/mail-gpg-0.3.0/lib/mail/gpg/gpgme_helper.rb:79:in `sign'
ruby/2.3.0/gems/mail-gpg-0.3.0/lib/mail/gpg/sign_part.rb:6:in `initialize'
ruby/2.3.0/gems/mail-gpg-0.3.0/lib/mail/gpg/signed_part.rb:29:in `new'
ruby/2.3.0/gems/mail-gpg-0.3.0/lib/mail/gpg/signed_part.rb:29:in `sign'
ruby/2.3.0/gems/mail-gpg-0.3.0/lib/mail/gpg.rb:55:in `block in sign'
ruby/2.3.0/gems/mail-gpg-0.3.0/lib/mail/gpg.rb:113:in `instance_eval'
ruby/2.3.0/gems/mail-gpg-0.3.0/lib/mail/gpg.rb:113:in `block in construct_mail'
ruby/2.3.0/gems/mail-2.6.4/lib/mail/message.rb:133:in `instance_eval'
ruby/2.3.0/gems/mail-2.6.4/lib/mail/message.rb:133:in `initialize'
ruby/2.3.0/gems/mail-2.6.4/lib/mail/mail.rb:51:in `new'
ruby/2.3.0/gems/mail-2.6.4/lib/mail/mail.rb:51:in `new'
ruby/2.3.0/gems/mail-gpg-0.3.0/lib/mail/gpg.rb:106:in `construct_mail'
ruby/2.3.0/gems/mail-gpg-0.3.0/lib/mail/gpg.rb:52:in `sign'
ruby/2.3.0/gems/mail-gpg-0.3.0/lib/mail/gpg/delivery_handler.rb:13:in `deliver_mail'
ruby/2.3.0/gems/mail-gpg-0.3.0/lib/mail/gpg/rails/action_mailer_base_patch.rb:31:in `block in deliver_mail'
ruby/2.3.0/gems/actionmailer-4.2.8/lib/action_mailer/base.rb:543:in `block in deliver_mail'
ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
ruby/2.3.0/gems/actionmailer-4.2.8/lib/action_mailer/base.rb:541:in `deliver_mail'
ruby/2.3.0/gems/mail-gpg-0.3.0/lib/mail/gpg/rails/action_mailer_base_patch.rb:30:in `deliver_mail'
ruby/2.3.0/gems/mail-2.6.4/lib/mail/message.rb:237:in `deliver'
ruby/2.3.0/gems/actionmailer-4.2.8/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
ruby/2.3.0/gems/actionmailer-4.2.8/lib/action_mailer/delivery_job.rb:10:in `perform'
ruby/2.3.0/gems/activejob-4.2.8/lib/active_job/execution.rb:32:in `block in perform_now'
[...]
```

Does anyone else experience this kind of problems?

**Comment by corny** [comment]
Due rotation of release directories the GNUPG home became inexistent. Sorry, our mistake.
